name: matrix-example
on: push

jobs:
  node-version:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node_version: [{v: 6, p: "version 6"}, {v: 8, p: "version 8"}, {v: 10, p: "version 10"} ]
        include:
          - os: ubuntu-latest
            node_version: {v: 6, p: "version 6"}
            is_ubuntu_8: "true"
        exclude:
          - os: ubuntu-latest
            node_version: {v: 8, p: "version 8"}
          - os: ubuntu-latest
            node_version: {v: 10, p: "version 10"}
      fail-fast: true
      max-parallel: 2
    runs-on: ${{ matrix.os }}
    env:
      IS_UBUNTU_8: ${{ matrix.is_ubuntu_8 }}
    steps:
      - name: log node version
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version.v }}
      - name: Log node version
        run: |
          node -v
          echo ${{ matrix.node_version.p }}
          echo $IS_UBUNTU_8

