name: matrix-example
on: push

jobs:
  node-version:
    strategy:
      matrix:
#        os: [macos-latest, ubuntu-latest, windows-latest]
        node_version: [{v: 6, p: "version 6"}, {v: 8, p: "version 8"}, {v: 10, p: "version 8"} ]
      fail-fast: true
      max-parallel: 2
    runs-on: macos-latest
    steps:
      - name: log node version
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version.v }}
      - name: Log node version
        run: node -v
      - name: print custom message
        run: echo ${{ matrix.node_version.p }}

