name: Actions workflow

on:
  #  schedule:
  #    # Min is 5minutes
  #    - cron: "0/5 * * * *"
  push
  #    paths:
  #      - *
  repository_dispatch:
    types: ["build"]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: Run shell command
        run: echo "hello world"
      - name: Run command from payload from dispatch
        run: echo ${{ github.event.client_payload.env }}
      - name: Run multiple shell command
        run: |
          echo "hello 2"
          pwd

      - name: run on action
        uses: actions/checkout@v3

  run-something-else:
    runs-on: macos-latest
    steps:
      - name: Print OS
        run: echo $OSTYPE
